baseURL = "https://marinhero.com/"
languageCode = "en-us"
title = "Marín Alcaraz"
theme = "clarity"

[params]
  description = "Software engineer, writer, and thinker. Writing about technology, systems, and ideas."
  mainSections = ["posts"]
  copyright = "Marín Alcaraz"

[languages]
  [languages.en]
    languageName = "English"
    title = "Marín's - Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [params.twitter]
      creator = "marinftw"
      site = "https://marinhero.com"

    [languages.en.params.logo]
      logoText = "Marín Alcaraz"
      logoHomeLink = "/"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/marin"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/pages/projects"
    weight = 2