baseURL = "https://marinhero.com/"
languageCode = "en-us"
title = "Marin Alcaraz"
theme = ["marin", "terminal"]

[params]
  contentTypeName = "posts"
  themeColor = "blue" # ["orange", "blue", "red", "green", "pink"]
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Marín's - Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [params.twitter]
      creator = "marinhero"
      site = "https://marinhero.com"

    [languages.en.params.logo]
      logoText = "Marín Alcaraz"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/pages/marin"
      [[languages.en.menu.main]]
        identifier = "adventure"
        name = "Adventure Blog"
        url = "/adventure"