baseURL = "https://marinhero.com/"
languageCode = "en-us"
title = "Marin Alcaraz"
theme = ["marin", "terminal"]

[params]
  mainSections = ["posts", "photo"]
  themeColor = "blue" # ["orange", "blue", "red", "green", "pink"]
  showMenuItems = 3
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Marín's - Blog"

    [languages.en.params.logo]
      logoText = "Marín Alcaraz"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/pages/marin"
      [[languages.en.menu.main]]
        identifier = "photos"
        name = "Photos"
        url = "/photos"
